### ISSUE TITLE
Link documentation

### ISSUE THREAD

**Issue by aurorarossi** [fargolo/TextGraphs.jl#6]
Hello!
I clicked on the link of the documentation in the README but it is not working.

**Comment by fargolo** [comment]
@aurorarossi , The link seems to be working for me: https://fargolo.github.io/TextGraphs.jl/dev/
Can you provide further details about the error?

**Comment by aurorarossi** [comment]
Here, if I click on  documentation blue link in the quick introduction:
![image](https://user-images.githubusercontent.com/65721467/202478607-f996e8e2-0436-4e70-a115-2fc9c1ecbbe5.png)
this  happens:
![image](https://user-images.githubusercontent.com/65721467/202479155-737af4cc-03a7-4571-97d8-7f53e24a2059.png)

**Comment by fargolo** [comment]
Thank you. I wrote the links as if they were images (with exclamation marks). 
```
![image](image/path)
```
Instead of 
```
[link](link/path)
```
It should work now.

**Comment by aurorarossi** [comment]
yes!
